### ISSUE TITLE
UI error in tubscreen

### ISSUE THREAD

**Issue by DocGarbanzo** [DocGarbanzo/donkeycar#4]
"/home/chris/donkeycar/donkeycar/management/kivy_ui.py", line 444, in step
     new_index = self.screen.index + (1 if fwd else -1)
 TypeError: unsupported operand type(s) for +: 'NoneType' and ‘int'

**Comment by half-freez** [comment]
hi DocGarbanzo, 
i've got problem when to launch  $donkey ui

and the error is like this

object address  : 0x7f97209e2ce0
object refcount : 2
object type     : 0x874ce0
object type name: RecursionError
object repr     : RecursionError('maximum recursion depth exceeded')
lost sys.stderr

**Comment by DocGarbanzo** [comment]
> hi DocGarbanzo, i've got problem when to launch $donkey ui
> 
> and the error is like this
> 
> object address : 0x7f97209e2ce0 object refcount : 2 object type : 0x874ce0 object type name: RecursionError object repr : RecursionError('maximum recursion depth exceeded') lost sys.stderr

Can you please check w/ the latest version and create a new issue if you still run into problems. Please copy / paste a full shell output in that case. This issue is old and has been resolved some time ago, so I'll close this.
